import test from 'node:test';
import assert from 'node:assert/strict';
import { resolveOutputGeometry,parseRatio } from '../src/core/output-geometry.js';
import { seedModels } from '../src/core/models.js';
import { ModuleRegistry } from '../src/core/modules.js';
import type { Recipe } from '../src/core/domain.js';
function fixture(){const registry=new ModuleRegistry(),model=seedModels()[3];model.geometry_support='size';const recipe:Recipe={recipe_id:'recipe_test',schema_version:1,modules:['subject','composition','composition','style','prompt'].map(type=>registry.create(type)),model_config_id:model.model_config_id,core_parameters:{...model.defaults,aspect_ratio:'auto'}};recipe.modules[0].asset_ids=['asset_subject'];recipe.modules[1].asset_ids=['asset_comp','asset_other'];recipe.modules[2].asset_ids=['asset_other'];const assets=[{asset_id:'asset_subject',width:1024,height:1024},{asset_id:'asset_comp',width:1370,height:900},{asset_id:'asset_other',width:1024,height:1536}];return {recipe,model,assets};}
test('自动优先构图，按模块与图片顺序取第一，不修改输入数组',()=>{const {recipe,model,assets}=fixture(),before=structuredClone(recipe);const g=resolveOutputGeometry(recipe,assets,model);assert.equal(g.basis,'composition');assert.equal(g.asset_id,'asset_comp');assert.equal(g.ratio,'137:90');assert.equal(g.target,'size');assert.equal(g.request_size,'2192x1440');assert.deepEqual(recipe,before);
  [recipe.modules[1],recipe.modules[2]]=[recipe.modules[2],recipe.modules[1]];assert.equal(resolveOutputGeometry(recipe,assets,model).asset_id,'asset_other');
});
test('停用及空构图不影响优先级，依次主体、模型自动；风格图不成为尺寸依据',()=>{const {recipe,model,assets}=fixture();recipe.modules[1].enabled=false;recipe.modules[2].asset_ids=[];const g=resolveOutputGeometry(recipe,assets,model);assert.equal(g.basis,'subject');assert.equal(g.request_ratio,'1:1');recipe.modules[0].asset_ids=[];recipe.modules[3].asset_ids=['asset_other'];assert.deepEqual(resolveOutputGeometry(recipe,assets,model),{selection:'auto',basis:'model',target:'auto',adjustments:[]});});
test('不能表达的任意比例退回模型自动并提示，不吸附为规范比例',()=>{const {recipe,model,assets}=fixture();model.geometry_support='ratio';const g=resolveOutputGeometry(recipe,assets,model);assert.equal(g.target,'auto');assert.equal(g.request_ratio,undefined);assert.equal(g.ratio,'137:90');assert.equal(g.adjustments.length,1);model.geometry_support='size';assets[1].width=1000;assets[1].height=701;assert.equal(resolveOutputGeometry(recipe,assets,model).target,'auto');});
test('固定与自定义覆盖自动选择；受限尺寸保留比例，越界自定义作为期望降级',()=>{const {recipe,model,assets}=fixture();recipe.core_parameters.aspect_ratio='2:3';const fixed=resolveOutputGeometry(recipe,assets,model);assert.equal(fixed.selection,'fixed');assert.equal(fixed.basis,'user');assert.equal(fixed.request_ratio,'2:3');recipe.core_parameters.aspect_ratio='custom:5:3';const custom=resolveOutputGeometry(recipe,assets,model);assert.equal(custom.selection,'custom');assert.equal(custom.target,'size');const [w,h]=custom.request_size!.split('x').map(Number);assert.equal(w/h,5/3);assert.equal(w%16,0);recipe.core_parameters.aspect_ratio='custom:10:1';assert.equal(resolveOutputGeometry(recipe,assets,model).target,'auto');for(const value of ['0:1','NaN:1','-2:3','1:0','5/3'])assert.equal(parseRatio(value),null);assert.throws(()=>{recipe.core_parameters.aspect_ratio='custom:0:1';resolveOutputGeometry(recipe,assets,model);});});
