import { forwardRef,useEffect,useImperativeHandle,useRef,useState } from 'react';
import { newId } from '../core/domain.js';
import type { PublicConnection } from '../core/model-library.js';
import type { Command,WorkspaceView,ApiResponse } from '../shared/api.js';
import { ModelSettingsEditor,type DraftHandle } from './ModelSettingsEditor.js';
import { PlatformDrawer } from './PlatformDrawer.js';
import { AppDialog } from './AppDialog.js';
import { SettingsConfirmation } from './SettingsConfirmation.js';
import './model-settings.css';

export interface SettingsPageHandle {requestClose:()=>void}
export const ModelSettingsPage=forwardRef<SettingsPageHandle,{view:WorkspaceView;initialModel?:string;onClose:()=>void;onSave:(command:Command)=>Promise<boolean>;onProbe:(command:Command)=>Promise<ApiResponse>}>(function ModelSettingsPage({view,initialModel,onClose,onSave,onProbe},ref){
  const [platform,setPlatform]=useState('all'),[selected,setSelected]=useState(initialModel??view.models.find(m=>m.kind==='cloud')?.model_config_id??view.models[0]?.model_config_id??''),[platformQuery,setPlatformQuery]=useState(''),[modelQuery,setModelQuery]=useState('');
  const [connection,setConnection]=useState<PublicConnection|null>(null),[busy,setBusy]=useState(false),[pending,setPending]=useState<(()=>void)|null>(null),[editorVersion,setEditorVersion]=useState(0);
  const [removal,setRemoval]=useState<{command:Command;title:string;description:string;label:string}|null>(null);
  const saving=useRef(false);
  const editor=useRef<DraftHandle>(null),drawer=useRef<DraftHandle>(null),root=useRef<HTMLElement>(null);
  const currentDraft=()=>connection?drawer.current:editor.current;
  const guard=(action:()=>void)=>{if(saving.current||removal)return;if(currentDraft()?.dirty)setPending(()=>action);else action();};
  useImperativeHandle(ref,()=>({requestClose:()=>guard(onClose)}));
  const save=async(command:Command)=>{if(saving.current)return false;saving.current=true;setBusy(true);try{return await onSave(command);}finally{saving.current=false;setBusy(false);}};
  const models=view.models.filter(m=>(platform==='all'||platform==='local'&&m.kind!=='cloud'||m.connection_id===platform)&&`${m.title} ${m.model}`.toLowerCase().includes(modelQuery.toLowerCase()));
  const model=view.models.find(m=>m.model_config_id===selected);
  useEffect(()=>{if(!model)setSelected(models[0]?.model_config_id??'');},[model,models]);
  const choosePlatform=(id:string)=>guard(()=>{setPlatform(id);setSelected(view.models.find(m=>id==='all'||id==='local'&&m.kind!=='cloud'||m.connection_id===id)?.model_config_id??'');});
  const editConnection=(c?:PublicConnection)=>guard(()=>setConnection(c??{connection_id:newId('connection'),title:'新接口平台',endpoint:'',enabled:true,revision:1,has_credential:false,adapter_id:'gemini-generate-content'}));
  // Trap keyboard focus in the topmost drawer / unsaved-changes dialog.
  useEffect(()=>{if(!connection&&!pending&&!removal)return;const node=root.current;const handle=(event:KeyboardEvent)=>{if(event.key!=='Tab')return;const dialogs=Array.from(node?.querySelectorAll<HTMLElement>('[role="dialog"]')??[]).filter(el=>!el.closest('[inert]'));const top=dialogs.at(-1);const controls=Array.from(top?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),summary,a[href]')??[]).filter(el=>el.getClientRects().length>0);if(!controls.length)return;const first=controls[0],last=controls[controls.length-1];if(event.shiftKey&&(document.activeElement===first||!top?.contains(document.activeElement))){event.preventDefault();last.focus();}else if(!event.shiftKey&&(document.activeElement===last||!top?.contains(document.activeElement))){event.preventDefault();first.focus();}};node?.addEventListener('keydown',handle);return()=>node?.removeEventListener('keydown',handle);},[connection,pending,removal]);
  return <section className="global-settings" ref={root} aria-label="全局设置">
    <div className="settings-page-heading" inert={connection||pending||removal?true:undefined}><div><span className="settings-eyebrow">全局设置</span><h1>模型设置</h1></div>{busy&&<span role="status">正在处理…</span>}<button disabled={busy} onClick={()=>guard(onClose)}>返回工作台</button></div>
    <div className="settings-columns" inert={connection||pending||removal||busy?true:undefined}>
      <aside className="settings-platforms"><div className="settings-section-heading"><h2>接口平台</h2><button onClick={()=>editConnection()}>＋ 新建</button></div><input aria-label="搜索接口平台" placeholder="搜索平台…" value={platformQuery} onChange={e=>setPlatformQuery(e.target.value)}/><button className={`platform-row ${platform==='all'?'selected':''}`} onClick={()=>choosePlatform('all')}><b>全部平台</b><small>{view.models.filter(m=>m.kind==='cloud').length} 个云端模型接入</small></button>{view.connections?.filter(c=>c.title.toLowerCase().includes(platformQuery.toLowerCase())).map(c=><div className="platform-entry" key={c.connection_id}><button className={`platform-row ${platform===c.connection_id?'selected':''}`} onClick={()=>choosePlatform(c.connection_id)}><b>{c.title}</b><small>{!c.enabled?'已停用':c.has_credential?'密钥已配置':'待填写密钥'}</small></button><button className="platform-edit" aria-label={`配置平台 ${c.title}`} onClick={()=>editConnection(c)}>⚙</button></div>)}<button className={`platform-row ${platform==='local'?'selected':''}`} onClick={()=>choosePlatform('local')}><b>模拟与本地</b><small>本地验证入口</small></button></aside>
      <section className="settings-models"><div className="settings-section-heading"><h2>已入库模型 <small>{models.length}</small></h2><button onClick={()=>editConnection(view.connections?.find(c=>c.connection_id===platform)??view.connections?.[0])}>＋ 入库</button></div><input aria-label="搜索已入库模型" placeholder="搜索模型…" value={modelQuery} onChange={e=>setModelQuery(e.target.value)}/>{models.map(m=><button key={m.model_config_id} className={`settings-model-row ${selected===m.model_config_id?'selected':''}`} onClick={()=>guard(()=>setSelected(m.model_config_id))}><span className="settings-model-kind">{m.purpose==='understanding'?'推理':'生图'}{view.assignments?.[`${m.purpose??'generation'}_default`]===m.model_config_id?' · 默认':''}{view.assignments?.editing_default===m.model_config_id?' · 默认编辑':''}</span><b>{m.title}</b><small>{view.connections?.find(c=>c.connection_id===m.connection_id)?.title??'模拟与本地'}</small><small className={m.readiness_error?'settings-warning':''}>{m.enabled?m.executable?'已配置 · 可尝试调用':m.readiness_error??'待配置':'已停用'}</small></button>)}{!models.length&&<p className="settings-empty">尚无模型。配置接口平台后，选择模型预设即可入库。</p>}</section>
      <section className="settings-model-detail" aria-label="模型参数设置">{model?<ModelSettingsEditor key={`${selected}:${editorVersion}`} ref={editor} model={model} view={view} save={save} busy={busy} onRemove={()=>setRemoval({command:{type:'model:delete',model_config_id:model.model_config_id},title:'移除模型接入',description:`移除「${model.title}」的当前接口接入？已有工作记录和生成结果会保留。`,label:'确认移除'})}/>:<div className="settings-empty"><h2>选择一个模型</h2><p>在这里调整它的默认参数。</p></div>}</section>
    </div>
    {connection&&<div className="settings-drawer-container" inert={pending||removal?true:undefined}><PlatformDrawer key={connection.connection_id} ref={drawer} connection={connection} view={view} save={save} probe={onProbe} busy={busy} onClose={()=>guard(()=>{setConnection(null);setEditorVersion(v=>v+1);})} onRemove={()=>setRemoval({command:{type:'connection:delete',connection_id:connection.connection_id},title:'删除接口平台',description:`删除「${connection.title}」？仍有关联模型的平台无法删除。`,label:'确认删除'})} onEnrolled={id=>{setSelected(id);setPlatform(connection.connection_id);}}/></div>}
    {removal&&<SettingsConfirmation title={removal.title} description={removal.description} confirmLabel={removal.label} onCancel={()=>setRemoval(null)} onConfirm={async()=>{const ok=await save(removal.command);if(ok){if(removal.command.type==='connection:delete'){setConnection(null);setPlatform('all');setEditorVersion(v=>v+1);}setRemoval(null);}return ok;}}/>}
    {pending&&<AppDialog title="设置尚未保存" onDismiss={()=>setPending(null)} actions={[{label:'取消',run:()=>setPending(null)},{label:'放弃修改',run:()=>{const next=pending;setPending(null);setEditorVersion(v=>v+1);next();}},{label:'保存并继续',primary:true,run:async()=>{if(await currentDraft()?.save()){const next=pending;setPending(null);setEditorVersion(v=>v+1);next();}else throw new Error('设置尚未保存，请检查输入后重试。');}}]}>保存后继续，或放弃这次修改。</AppDialog>}
  </section>;
});
