import { maskEditMethod } from '../core/mask-request.js';
import { forwardRef,useImperativeHandle,useState } from 'react';
import { defaultImagesCompatibility,type ModelConfig,type PublicModel } from '../core/domain.js';
import type { ModelEntry } from '../core/model-library.js';
import type { Command,WorkspaceView } from '../shared/api.js';
import { findPreset,modelCatalog } from '../protocols/model-catalog.js';
import { normalizeParameters } from '../core/generation-parameters.js';
import { ModelParametersForm } from './ModelParametersForm.js';
import {imagesUploadLimits,MAX_IMAGES_FILE_MB,MAX_IMAGES_REQUEST_MB,geminiUploadLimits,MAX_GEMINI_REQUEST_MB} from '../core/image-limits.js';

export interface DraftHandle {dirty:boolean;save:()=>Promise<boolean>}
export const ModelSettingsEditor=forwardRef<DraftHandle,{model:PublicModel;view:WorkspaceView;save:(c:Command)=>Promise<boolean>;busy:boolean;onRemove:()=>void}>(function ModelSettingsEditor({model,view,save,busy,onRemove},ref){
  const initial=():Omit<ModelEntry,'revision'>=>({model_config_id:model.model_config_id,title:model.title,kind:model.kind,provider:model.provider,model:model.model,adapter_id:model.adapter_id,connection_id:model.connection_id,purpose:model.purpose??'generation',capability_source:model.capability_source==='tested'?'user':model.capability_source??'documented',enabled:model.enabled,capabilities:structuredClone(model.declared_capabilities??model.capabilities),generation_contract:model.generation_contract,defaults:structuredClone(model.defaults),preset_id:model.preset_id,legacy_defaults_pending:model.legacy_defaults_pending,images_compatibility:model.images_compatibility,gemini_compatibility:model.gemini_compatibility});
  const [draft,setDraft]=useState(initial),[baseline,setBaseline]=useState(()=>JSON.stringify(initial()));
  const dirty=JSON.stringify(draft)!==baseline;
  const preset=findPreset(draft.preset_id),resolved={...model,...draft,endpoint:model.endpoint,executable:model.executable} as ModelConfig;
  const patch=(v:Partial<typeof draft>)=>setDraft(m=>({...m,...v}));
  const operationEnabled=(operation:string)=>!draft.capabilities.disabled_operations?.includes(operation)&&(draft.capabilities.operations.includes(operation)||!!preset?.config.capabilities.operations.includes(operation));
  const setOperation=(operation:string,enabled:boolean)=>patch({capability_source:'user',capabilities:{...draft.capabilities,operations:[...draft.capabilities.operations.filter(op=>op!==operation),...(enabled?[operation]:[])],disabled_operations:[...(draft.capabilities.disabled_operations??[]).filter(op=>op!==operation),...(!enabled?[operation]:[])]}});
  const persist=async()=>{const ok=await save({type:'model:save',model:draft});if(ok)setBaseline(JSON.stringify(draft));return ok;};
  useImperativeHandle(ref,()=>({dirty,save:persist}));
  const selectPreset=(id:string)=>{const p=findPreset(id);if(!p)return;const peer=view.models.find(m=>m.preset_id===id&&!m.legacy_defaults_pending);patch({...structuredClone(p.config),preset_id:id,purpose:p.purpose,capability_source:'documented',defaults:structuredClone(peer?.defaults??p.config.defaults)});};
  const isDefault=view.assignments?.[`${draft.purpose}_default`]===draft.model_config_id;
  const isEditingDefault=view.assignments?.editing_default===draft.model_config_id;
  // Assignment acts on the saved model; use its effective preset/adapter
  // capabilities, not the editable legacy declarations. Dirty drafts cannot assign.
  const canBeEditingDefault=!!maskEditMethod(model);
  const parameters=normalizeParameters(draft.defaults,resolved);
  return <div className="settings-editor">
    <header className="settings-detail-heading"><div><span className="settings-eyebrow">{draft.purpose==='understanding'?'推理模型':'生图模型'}</span><h2>{draft.title}</h2><p>{view.connections?.find(c=>c.connection_id===draft.connection_id)?.title??'模拟与本地'} · {draft.model}</p></div><span className="settings-status">{dirty?'未保存':model.executable?'已配置':'待配置'}</span></header>
    <label>模型显示名称<input value={draft.title} maxLength={100} onChange={e=>patch({title:e.target.value})}/></label>
    {draft.kind==='cloud'&&<label>对应模型预设<select aria-label="对应模型预设" value={draft.preset_id??''} onChange={e=>selectPreset(e.target.value)}><option value="" disabled>旧配置／自定义模型</option>{modelCatalog.filter(p=>p.config.adapter_id===draft.adapter_id).map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label>}
    {model.legacy_defaults_pending&&<p className="settings-notice">该型号的旧渠道配置存在不同默认值。此处保留了当前条目的值；保存后，将这套参数设为该型号的共用默认值。旧工作流程不变。</p>}
    {!preset&&draft.kind==='cloud'&&<p className="settings-notice">旧设置已保留。选择具体模型预设，可自动补齐比例、分辨率等选项；保存后生效。</p>}
    {preset&&<p className="settings-hint">此型号共用的默认参数 · 用于新工作流程。已有工作流程独立保存。</p>}
    <section><h3>{draft.purpose==='understanding'?'默认推理参数':'默认生图参数'}</h3><ModelParametersForm model={resolved} value={parameters} onChange={defaults=>patch({defaults})}/></section>
    <details><summary>模型信息与能力</summary><p className="settings-hint">{draft.purpose==='generation'?`比例：${draft.capabilities.aspect_ratios.join('、')}。`:'支持图片与文字理解。'} 参考图上限：{draft.capabilities.max_images} 张（当前接入范围）。</p>{preset&&<a href={preset.source} target="_blank" rel="noreferrer">查看官方说明</a>}<label className="settings-check"><input type="checkbox" checked={draft.enabled} onChange={e=>patch({enabled:e.target.checked})}/>启用此接口的模型</label></details>
    <details><summary>当前接口兼容设置</summary><p className="settings-hint">仅影响此渠道接入，不修改其他渠道。</p><label>渠道模型 ID<input value={draft.model} onChange={e=>patch({model:e.target.value})}/></label><p className="settings-hint">接口协议：{view.adapters?.find(a=>a.adapter_id===draft.adapter_id)?.title??draft.adapter_id}</p>
      {draft.adapter_id==='openai-images'&&<><label>输出格式字段<select value={(draft.images_compatibility??defaultImagesCompatibility).format_field} onChange={e=>patch({images_compatibility:{...(draft.images_compatibility??defaultImagesCompatibility),format_field:e.target.value as 'format'|'output_format'}})}><option value="output_format">output_format（官方）</option><option value="format">format（兼容）</option></select></label><label>参考图字段<select value={(draft.images_compatibility??defaultImagesCompatibility).image_field} onChange={e=>patch({images_compatibility:{...(draft.images_compatibility??defaultImagesCompatibility),image_field:e.target.value as 'image'|'image[]'}})}><option value="image[]">image[]（官方）</option><option value="image">image（兼容）</option></select></label><label className="settings-check"><input type="checkbox" checked={(draft.images_compatibility??defaultImagesCompatibility).send_response_format} onChange={e=>patch({images_compatibility:{...(draft.images_compatibility??defaultImagesCompatibility),send_response_format:e.target.checked}})}/>发送 response_format=b64_json</label><label>提示词字符上限<input type="number" min={1} max={32000} value={(draft.images_compatibility??defaultImagesCompatibility).max_prompt_chars} onChange={e=>patch({images_compatibility:{...(draft.images_compatibility??defaultImagesCompatibility),max_prompt_chars:Number(e.target.value)}})}/></label></>}
      {view.adapters?.find(a=>a.adapter_id===draft.adapter_id)?.operations.includes('nativeMaskEdit')&&<label className="settings-check"><input type="checkbox" checked={operationEnabled('nativeMaskEdit')} onChange={e=>setOperation('nativeMaskEdit',e.target.checked)}/>此渠道支持原生蒙版编辑</label>}
      {draft.adapter_id==='openai-images'&&<><label>单文件上限（MB）<input aria-label="单文件上限（MB）" type="number" min={1} max={MAX_IMAGES_FILE_MB} value={imagesUploadLimits(draft.images_compatibility).fileMB} onChange={e=>patch({images_compatibility:{...(draft.images_compatibility??defaultImagesCompatibility),max_image_mb:Number(e.target.value)}})}/></label><label>请求合计预算（MB）<input aria-label="请求合计预算（MB）" type="number" min={1} max={MAX_IMAGES_REQUEST_MB} value={imagesUploadLimits(draft.images_compatibility).requestMB} onChange={e=>patch({images_compatibility:{...(draft.images_compatibility??defaultImagesCompatibility),max_request_mb:Number(e.target.value)}})}/></label><p className="settings-hint">图片、蒙版与文字的本地发送预算，默认 50 MB。请按渠道实际限制调整；调大预算不代表上游支持。</p></>}
      {draft.adapter_id==='gemini-generate-content'&&<><label>内联请求预算（MB）<input aria-label="内联请求预算（MB）" type="number" min={1} max={MAX_GEMINI_REQUEST_MB} value={geminiUploadLimits(draft.gemini_compatibility).requestMB} onChange={e=>patch({gemini_compatibility:{...draft.gemini_compatibility,max_request_mb:Number(e.target.value)}})}/></label><p className="settings-hint">按编码后的完整请求计算，默认 100 MB；可按渠道限制调低。</p></>}
      {view.adapters?.find(a=>a.adapter_id===draft.adapter_id)?.operations.includes('guidedMaskEdit')&&draft.purpose==='generation'&&<label className="settings-check"><input type="checkbox" checked={operationEnabled('guidedMaskEdit')} onChange={e=>setOperation('guidedMaskEdit',e.target.checked)}/>启用黑白区域图引导编辑</label>}
      <label>渠道参考图上限<input type="number" min={0} max={preset?.config.capabilities.max_images??100} value={draft.capabilities.max_images} onChange={e=>patch({capabilities:{...draft.capabilities,max_images:Number(e.target.value)}})}/></label>
    </details>
    {model.readiness_error&&<p className="settings-notice">{model.readiness_error}</p>}
    <div className="settings-savebar"><button className="primary" disabled={busy||!draft.title.trim()||!draft.model.trim()} onClick={()=>void persist()}>保存默认设置</button><button disabled={busy||!preset} onClick={()=>preset&&patch({defaults:structuredClone(preset.config.defaults)})}>恢复官方推荐</button></div>
    <div className="settings-actions">{canBeEditingDefault&&<button disabled={busy||dirty||!draft.enabled||isEditingDefault} onClick={()=>void save({type:'model:assign',purpose:'editing',model_config_id:draft.model_config_id})}>{isEditingDefault?'已设为默认编辑模型':'设为默认编辑模型'}</button>}<button disabled={busy||dirty||isDefault||!draft.enabled} onClick={()=>void save({type:'model:assign',purpose:draft.purpose,model_config_id:draft.model_config_id})}>{isDefault?'当前默认模型':draft.purpose==='understanding'?'设为默认推理模型':'设为默认生图模型'}</button><button disabled={busy||isDefault||isEditingDefault} onClick={onRemove}>移除接入</button></div>
    {draft.purpose==='understanding'&&<details><summary>推理链路测试</summary><p className="settings-hint">发送固定算术问题，可能计费。只验证文本推理，不代表图片理解已验证。</p><button disabled={busy||dirty||!model.executable} onClick={()=>void save({type:'model:test',model_config_id:model.model_config_id})}>测试推理链路（可能计费）</button>{view.model_tests?.filter(t=>t.model_config_id===model.model_config_id).slice(-3).reverse().map(t=><article key={t.test_id}><p>{t.status==='succeeded'?'测试成功':t.status==='running'?'测试中':'测试失败'} {t.error}</p>{t.status==='succeeded'&&<button disabled={busy} onClick={()=>void save({type:'model:accept-test',test_id:t.test_id})}>采用测试结果</button>}</article>)}</details>}
  </div>;
});
