import { forwardRef,useImperativeHandle,useState } from 'react';
import { newId } from '../core/domain.js';
import type { PublicConnection } from '../core/model-library.js';
import type { ApiResponse,Command,WorkspaceView } from '../shared/api.js';
import { identifyPreset,modelCatalog,modelFromPreset } from '../protocols/model-catalog.js';
import type { DraftHandle } from './ModelSettingsEditor.js';

export const PlatformDrawer=forwardRef<DraftHandle,{connection:PublicConnection;view:WorkspaceView;save:(c:Command)=>Promise<boolean>;probe:(c:Command)=>Promise<ApiResponse>;busy:boolean;onClose:()=>void;onRemove:()=>void;onEnrolled:(id:string)=>void}>(function PlatformDrawer({connection,view,save,probe,busy,onClose,onRemove,onEnrolled},ref){
  const [title,setTitle]=useState(connection.title),[endpoint,setEndpoint]=useState(connection.endpoint),[adapter,setAdapter]=useState(connection.adapter_id??view.models.find(m=>m.connection_id===connection.connection_id)?.adapter_id??'gemini-generate-content'),[enabled,setEnabled]=useState(connection.enabled),[secret,setSecret]=useState(''),[clear,setClear]=useState(false);
  const [baseline,setBaseline]=useState(()=>JSON.stringify([connection.title,connection.endpoint,connection.adapter_id??view.models.find(m=>m.connection_id===connection.connection_id)?.adapter_id??'gemini-generate-content',connection.enabled]));
  const [sub,setSub]=useState(false),[models,setModels]=useState<string[]>([]),[query,setQuery]=useState(''),[manual,setManual]=useState(''),[choices,setChoices]=useState<Record<string,string>>({}),[loading,setLoading]=useState(false),[message,setMessage]=useState('');
  const dirty=baseline!==JSON.stringify([title,endpoint,adapter,enabled])||!!secret||clear||!view.connections?.some(c=>c.connection_id===connection.connection_id);
  const persist=async()=>{const ok=await save({type:'connection:save',connection:{connection_id:connection.connection_id,title,endpoint,enabled,adapter_id:adapter},...(secret?{secret}:{}),clear_credential:clear});if(ok){setSecret('');setClear(false);setBaseline(JSON.stringify([title,endpoint,adapter,enabled]));}return ok;};
  useImperativeHandle(ref,()=>({dirty,save:persist}));
  const openList=async(fetchList:boolean)=>{setMessage('');if(dirty&&!await persist())return;setSub(true);if(!fetchList)return;setLoading(true);try{const result=await probe({type:'connection:probe',connection_id:connection.connection_id,adapter_id:adapter});if(result.ok){setModels(result.discovered_models??[]);setMessage(result.discovered_models?.length?'已获取模型名称，尚未验证实际调用。':'接口未返回模型，可以手动添加。');}else setMessage(result.error??'获取失败，可以手动添加。');}catch{setMessage('获取失败，可以手动添加。');}finally{setLoading(false);}};
  const available=modelCatalog.filter(p=>p.config.adapter_id===adapter);
  const renderRow=(id:string)=>{const matched=identifyPreset(id),selected=choices[id]??(matched?.config.adapter_id===adapter?matched.id:''),exists=view.models.some(m=>m.connection_id===connection.connection_id&&m.model===id&&m.adapter_id===adapter);
    return <div className="discovery-row" key={id}><span title={id}>{id}</span><select aria-label={`${id} 模型预设`} disabled={exists||busy} value={selected} onChange={e=>setChoices(c=>({...c,[id]:e.target.value}))}><option value="">选择模型预设</option>{(['nano','gpt-image','reasoning'] as const).map(f=><optgroup key={f} label={{nano:'Nano Banana 系列','gpt-image':'GPT Image 系列',reasoning:'推理模型'}[f]}>{available.filter(p=>p.family===f).map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</optgroup>)}</select><button disabled={exists||!selected||busy||loading} onClick={async()=>{const {endpoint:_,executable:__,revision:___,...model}=modelFromPreset(selected,newId('model'),connection.connection_id,id);const ok=await save({type:'model:save',model:{...model,purpose:available.find(p=>p.id===selected)!.purpose,capability_source:'documented'}});if(ok){onEnrolled(model.model_config_id);setMessage('已入库，完整参数选项已自动配置。');}}}>{exists?'已在库':'＋ 入库'}</button></div>;
  };
  return <div className={`settings-drawer-layer ${sub?'has-sub':''}`} onKeyDown={e=>{if(e.key==='Escape'&&!busy&&!loading){e.stopPropagation();if(sub)setSub(false);else onClose();}}}>
    <section className="platform-drawer" role="dialog" aria-label="接口平台配置" aria-modal={!sub} inert={sub?true:undefined}>
      <header><div><span className="settings-eyebrow">接口与模型配置</span><h2>{title||'新接口平台'}</h2></div><button aria-label="关闭接口配置" disabled={busy||loading} onClick={onClose}>×</button></header>
      <div className="drawer-content"><label>平台名称<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} maxLength={100}/></label><label>接口类型<select value={adapter} onChange={e=>{setAdapter(e.target.value);setModels([]);setChoices({});}}>{view.adapters?.filter(a=>a.kind==='cloud'&&a.supports_probe).map(a=><option key={a.adapter_id} value={a.adapter_id}>{a.title}</option>)}</select></label><label>API 地址<input value={endpoint} onChange={e=>setEndpoint(e.target.value)} placeholder="https://api.example.com"/></label><label>API Key<input type="password" autoComplete="off" value={secret} disabled={clear} placeholder={connection.has_credential?'已加密保存，留空保留':'填写接口密钥'} onChange={e=>setSecret(e.target.value)}/></label><label className="settings-check"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>启用平台</label>
        <div className="settings-actions"><button className="primary" disabled={busy||loading||!title.trim()||!endpoint.trim()} onClick={()=>void openList(true)}>{loading?'正在获取…':'保存并获取模型列表'}</button><button disabled={busy||loading||!title.trim()||!endpoint.trim()} onClick={()=>void openList(false)}>手动入库</button></div><p className="settings-hint">获取列表不会发起生图。密钥由本机加密保存。</p>
        <details><summary>平台管理</summary><label className="settings-check"><input type="checkbox" checked={clear} onChange={e=>{setClear(e.target.checked);setSecret('');}}/>清除已保存的密钥</label><div className="settings-actions"><button disabled={busy||loading||!title.trim()||!endpoint.trim()} onClick={()=>void persist()}>保存平台</button><button disabled={busy||loading||!view.connections?.some(c=>c.connection_id===connection.connection_id)} onClick={onRemove}>删除平台</button></div></details>
      </div>
    </section>
    {sub&&<section className="discovery-drawer" role="dialog" aria-modal="true" aria-label="模型入库"><header><div><h2>模型入库</h2><p>{models.length?`获取到 ${models.length} 个模型`:'选择系列预设后添加模型'}</p></div><button aria-label="关闭模型入库" disabled={busy||loading} onClick={()=>setSub(false)}>×</button></header><div className="drawer-content"><input autoFocus aria-label="筛选模型" placeholder="搜索模型名称…" value={query} onChange={e=>setQuery(e.target.value)}/><p className="settings-hint" role="status">{loading?'正在读取模型列表…':message||'自动匹配已知型号；未识别时选择具体预设。'}</p><div className="discovery-list">{models.filter(id=>id.toLowerCase().includes(query.toLowerCase())).map(renderRow)}</div><div className="manual-model"><label>手动填写模型 ID<input value={manual} onChange={e=>setManual(e.target.value)} maxLength={100} placeholder="渠道提供的实际模型名称"/></label>{manual.trim()&&renderRow(manual.trim())}</div></div></section>}
  </div>;
});
