import { z } from 'zod';
import { idSchema, recipeSchema } from '../core/domain.js';
import { connectionSchema, modelEntrySchema } from '../core/model-library.js';
import { maskDraftSchema,maskModeSchema,maskStrokesSchema } from '../core/mask.js';

export const commandSchema = z.discriminatedUnion('type', [
  z.object({type:z.literal('mask:save-composite'),project_id:idSchema,task_id:idSchema,strokes:maskStrokesSchema}),
  z.object({type:z.literal('mask:preview'),project_id:idSchema,task_id:idSchema,mode:maskModeSchema,feather:z.number().int().min(0).max(64),composite_strokes:maskStrokesSchema.optional()}),
  z.object({type:z.literal('mask:save-draft'),project_id:idSchema,draft:maskDraftSchema}),
  z.object({type:z.literal('mask:start'),project_id:idSchema,draft:maskDraftSchema}),
  z.object({type:z.literal('mask:reprocess'),project_id:idSchema,task_id:idSchema,mode:maskModeSchema,feather:z.number().int().min(0).max(64),composite_strokes:maskStrokesSchema.optional()}),
  z.object({type:z.literal('recipe:select-model'),model_config_id:idSchema}),
  z.object({type:z.literal('recipe:reset-parameters')}),
  z.object({type:z.literal('module:infer'),request_id:idSchema,project_id:idSchema,module_id:idSchema,model_config_id:idSchema,text:z.string().max(32000),allow_text_only:z.boolean()}),
  z.object({type:z.literal('module:cancel-inference'),request_id:idSchema}),
  z.object({type:z.literal('job:model-input'),task_id:idSchema}),
  z.object({type:z.literal('model:test'),model_config_id:idSchema}),
  z.object({type:z.literal('model:accept-test'),test_id:idSchema}),
  z.object({type:z.literal('job:recover-result'),task_id:idSchema}),
  z.object({type:z.literal('connection:save'),connection:connectionSchema.omit({revision:true,credential_ref:true}),secret:z.string().max(1000).optional(),clear_credential:z.boolean().optional()}),
  z.object({type:z.literal('connection:delete'),connection_id:idSchema}),
  z.object({type:z.literal('model:save'),model:modelEntrySchema.omit({revision:true})}),
  z.object({type:z.literal('model:delete'),model_config_id:idSchema}),
  z.object({type:z.literal('model:assign'),purpose:z.enum(['generation','understanding','editing']),model_config_id:idSchema}),
  z.object({type:z.literal('connection:probe'),connection_id:idSchema,adapter_id:z.string().min(1).max(80)}),
  z.object({ type: z.literal('state') }),
  z.object({ type: z.literal('asset:hide'), asset_id:idSchema }),
  z.object({ type: z.literal('result:trash'), asset_id:idSchema }),
  z.object({ type: z.literal('result:restore'), project_id:idSchema, asset_id:idSchema }),
  z.object({ type: z.literal('workspace:remove'), id:z.string().regex(/^(work-[a-zA-Z0-9]{6}|file-[a-f0-9]{12})$/) }),
  z.object({ type: z.literal('workspace:rename'), id:z.string().regex(/^(work-[a-zA-Z0-9]{6}|file-[a-f0-9]{12})$/),name:z.string().trim().min(1).max(100) }),
  z.object({ type: z.literal('output:open') }),
  z.object({ type: z.literal('output:folder') }),
  z.object({ type: z.literal('project:create'), name: z.string().trim().min(1).max(100) }),
  z.object({ type: z.literal('project:open') }),
  z.object({ type: z.literal('project:save') }),
  z.object({ type: z.literal('recipe:save'), recipe: recipeSchema }),
  z.object({ type: z.literal('module:add'), reference_type: z.string().max(40), before_module_id: idSchema.optional() }),
  z.object({ type: z.literal('module:copy'), module_id: idSchema }),
  z.object({ type: z.literal('module:reference-type'), module_id: idSchema, reference_type: z.string().max(40) }),
  z.object({ type: z.literal('module:tool'), module_id: idSchema, png_base64: z.string().max(3_000_000), state: z.record(z.string().max(80),z.union([z.string().max(1000),z.number(),z.boolean()])).refine(s=>Object.keys(s).length<=64,'工具状态过大。'), instruction: z.string().max(32000) }),
  z.object({ type: z.literal('assets:import'), module_id: idSchema.optional() }),
  z.object({ type: z.literal('assets:drop'), paths: z.array(z.string().min(1).max(32768)).min(1).max(64), module_id: idSchema.optional() }),
  z.object({ type: z.literal('asset:relink'), asset_id: idSchema }),
  z.object({ type: z.literal('project:package') }),
  z.object({ type: z.literal('workspace:resume'), id: z.string().regex(/^(work-[a-zA-Z0-9]{6}|file-[a-f0-9]{12})$/) }),
  z.object({ type: z.literal('model:update'), model_config_id: idSchema, title: z.string().min(1).max(100), endpoint: z.string().max(500), enabled: z.boolean(), secret: z.string().max(1000).optional() }),
  z.object({ type: z.literal('job:start'), allow_degradation: z.boolean() }),
  z.object({type:z.literal('job:retry'),project_id:idSchema,task_id:idSchema}),
  z.object({ type: z.literal('job:cancel'), task_id: idSchema }),
  z.object({ type: z.literal('job:restore'), task_id: idSchema }),
  z.object({ type: z.literal('asset:export'), asset_id: idSchema }),
]);
